###
GET http://localhost:3000/api/canchas

###
get http://localhost:3000/api/turnos

###
post http://localhost:3000/api/tipos/


###
POST http://localhost:3000/api/tamanios/
Content-Type: application/json

{
    "capacidad_x_equipo": "7",
    "ancho": 25,
    "largo": 70
}

###
POST http://localhost:3000/api/tipos/
Content-Type: application/json

{
    "nombre": "futbol",
    "piso": "pasto",
    "techo": "sin_techo"
}


###
post http://localhost:3000/api/canchas
Content-Type: application/json

{
    "numero": 912,
    "nombre": "Lionel",
    "tipo_turno": "en_punto",
    "tamanio": 3,
    "tipo": 2,
    "turnos": [5,6]
}
//recordar que va el id para diferenciar el objeto


###
PATCH http://localhost:3000/api/canchas/1
Content-Type: application/json

{
    "tipo_turno": "y_media"
}

###
PATCH http://localhost:3000/api/tamanios/1
Content-Type: application/json

{
    "ancho": 2000
}

###
DELETE http://localhost:3000/api/canchas/4